# Generated by Django 3.2.13 on 2022-05-05 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('slug', models.CharField(max_length=50, verbose_name='分类英文名称')),
                ('active', models.BooleanField(default=False, verbose_name='是否添加到菜单')),
                ('icon', models.CharField(default='fa-home', max_length=30, verbose_name='菜单图标')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名称')),
                ('slug', models.CharField(default='74463977', max_length=50, unique=True, verbose_name='标签英文名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('summary', models.TextField(max_length=100, verbose_name='文章概述')),
                ('cover', models.CharField(default='https://image.3001.net/images/20200304/15832956271308.jpg', max_length=200, verbose_name='文章封面')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2022, 5, 6, 0, 15, 8, 249802), verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_id', models.CharField(default='20220506581749', editable=False, max_length=14, primary_key=True, serialize=False, verbose_name='文章编号')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='文章分类')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
            },
        ),
    ]
