# Generated by Django 3.2.13 on 2022-05-04 13:51

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('summary', models.TextField(max_length=100, verbose_name='文章概述')),
                ('cover', models.CharField(default='https://image.3001.net/images/20200304/15832956271308.jpg', max_length=200, verbose_name='文章封面')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_id', models.CharField(default='20220504084646', max_length=14, primary_key=True, serialize=False, verbose_name='文章编号')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
            },
        ),
    ]
