# Generated by Django 3.2.13 on 2022-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='20220504721048', max_length=14, primary_key=True, serialize=False, verbose_name='文章编号'),
        ),
    ]
