# Generated by Django 3.2.13 on 2022-05-05 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='20220506494752', editable=False, max_length=14, primary_key=True, serialize=False, verbose_name='文章编号'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.category', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 0, 22, 25, 614503), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='63328327', max_length=50, unique=True, verbose_name='标签英文名称'),
        ),
    ]
